/**
 * Comprehensive plant disease & pest knowledge base for Rwanda's key crops.
 * Each entry contains symptom keywords that the TF-IDF engine scores against
 * the farmer's text input and (for image entries) the visual feature descriptor
 * extracted from an uploaded photo.
 *
 * Sources: CABI Crop Protection Compendium, FAO Rwanda agronomy guides,
 * ISAR/RAB Rwanda crop disease bulletins, PlantVillage dataset labels.
 */

export interface DiseaseEntry {
  id: string;
  name: string;
  crops: string[]; // crop names this applies to (lower-case)
  category: 'FUNGAL' | 'BACTERIAL' | 'VIRAL' | 'PEST' | 'NUTRIENT' | 'WATER';
  symptoms: string; // rich text used for TF-IDF indexing
  visualSigns: string; // colour/texture/pattern cues for image analysis
  management: string;
  prevention: string;
  urgency: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  // Colour signals for local image analysis (0-360 hue ranges, 0-1 sat/val)
  imageHints?: {
    dominantHue?: [number, number]; // [min, max] hue degrees
    highNecrosis?: boolean; // dark-brown/black dead tissue
    lesionPattern?: 'SPOTS' | 'STRIPES' | 'BLIGHT' | 'MOSAIC' | 'WILT' | 'POWDER';
    yellowRatio?: 'HIGH' | 'MEDIUM'; // yellowing fraction
  };
}

export const PLANT_DISEASE_KB: DiseaseEntry[] = [
  // ─── MAIZE ────────────────────────────────────────────────────────────────
  {
    id: 'maize-gray-leaf-spot',
    name: 'Gray Leaf Spot',
    crops: ['maize', 'corn'],
    category: 'FUNGAL',
    symptoms: 'rectangular gray brown lesions parallel veins lower leaves tan gray rectangle stripes elongated necrotic long narrow angular',
    visualSigns: 'tan grey rectangular lesions running parallel to leaf veins on lower canopy',
    management: 'Apply fungicides (strobilurin or triazole) at early lesion stage. Remove crop debris after harvest. Plant resistant hybrids. Ensure good air circulation.',
    prevention: 'Use resistant varieties, rotate crops with legumes for 1-2 seasons, avoid dense planting.',
    urgency: 'MEDIUM',
    imageHints: { dominantHue: [20, 50], lesionPattern: 'STRIPES' },
  },
  {
    id: 'maize-northern-blight',
    name: 'Northern Corn Leaf Blight (NCLB)',
    crops: ['maize', 'corn'],
    category: 'FUNGAL',
    symptoms: 'long cigar shaped elliptical gray green lesions leaves entire leaf affected large grey lesions progressing upper canopy',
    visualSigns: 'large cigar-shaped grey-green lesions 2.5-15 cm long on leaves, starting mid-canopy',
    management: 'Apply foliar fungicides (mancozeb or propiconazole). Plant certified disease-resistant seed. Remove infected material.',
    prevention: 'Resistant varieties are most effective. Avoid overhead irrigation. Crop rotation.',
    urgency: 'HIGH',
    imageHints: { dominantHue: [40, 80], lesionPattern: 'BLIGHT' },
  },
  {
    id: 'maize-rust',
    name: 'Common Maize Rust',
    crops: ['maize', 'corn'],
    category: 'FUNGAL',
    symptoms: 'small circular oval cinnamon brown powdery pustules raised bumps both leaf surfaces rust orange powder reddish spores',
    visualSigns: 'small cinnamon/rust-orange powdery raised pustules scattered on both sides of leaves',
    management: 'Apply fungicide (mancozeb, chlorothalonil) at first pustule appearance. Use resistant hybrids. Remove heavily infected plants.',
    prevention: 'Plant rust-resistant varieties. Early planting avoids peak rust season.',
    urgency: 'MEDIUM',
    imageHints: { dominantHue: [15, 35], lesionPattern: 'SPOTS' },
  },
  {
    id: 'maize-streak-virus',
    name: 'Maize Streak Virus (MSV)',
    crops: ['maize', 'corn'],
    category: 'VIRAL',
    symptoms: 'yellow white streaks stripes along veins chlorotic streaking young leaves stunted growth pale yellowing striped seedlings leafhopper',
    visualSigns: 'bright yellow or white broken stripes running along the veins of young leaves',
    management: 'No cure for infected plants. Control leafhopper vectors with imidacloprid seed dressing. Remove and destroy infected seedlings. Plant tolerant varieties.',
    prevention: 'Use MSV-tolerant seed, plant early in season to miss vector peak, control leafhoppers.',
    urgency: 'HIGH',
    imageHints: { dominantHue: [55, 75], lesionPattern: 'STRIPES', yellowRatio: 'HIGH' },
  },
  {
    id: 'fall-armyworm',
    name: 'Fall Armyworm (FAW)',
    crops: ['maize', 'corn', 'sorghum', 'wheat'],
    category: 'PEST',
    symptoms: 'ragged holes leaves caterpillar larvae frass droppings inside whorl eaten tissue sawdust frass windowpane skeletonized young leaves',
    visualSigns: 'ragged holes in leaves, wet sawdust-like frass in the plant whorl, caterpillars with Y-shaped head marking',
    management: 'Apply Bt (Bacillus thuringiensis) spray or spinosad in the whorl at first detection. Neem-based insecticides effective on young larvae. Emamectin benzoate for severe cases.',
    prevention: 'Scout twice weekly, encourage natural predators (birds, parasitoids), apply sand/ash in whorl as early deterrent.',
    urgency: 'CRITICAL',
    imageHints: { highNecrosis: true, lesionPattern: 'BLIGHT' },
  },
  {
    id: 'maize-stem-borer',
    name: 'Maize Stem Borer',
    crops: ['maize', 'corn', 'sorghum'],
    category: 'PEST',
    symptoms: 'deadheart dead central shoot whorl holes bored tunnel stem eaten caterpillar entry holes frass droppings sawdust stalk lodging broken stem',
    visualSigns: 'central shoot dead (deadheart), entry holes with frass on stem, tunneling inside stalk',
    management: 'Apply granular insecticide (carbofuran, fipronil) in whorl at early instar. Bt formulations effective. Destroy crop residues. Use parasitoid wasps (Cotesia sesamiae).',
    prevention: 'Early planting, crop rotation, remove and burn old stalks, push-pull technology with Desmodium.',
    urgency: 'HIGH',
  },
  {
    id: 'maize-ear-rot',
    name: 'Fusarium Ear Rot',
    crops: ['maize', 'corn'],
    category: 'FUNGAL',
    symptoms: 'pink salmon white mold kernels ear tip rot pink cottony mold aflatoxin mycotoxin starburst pattern rotted cob',
    visualSigns: 'pink to salmon cottony mold on kernel tips, often with starburst white streaks on kernels',
    management: 'Harvest promptly when mature, dry grain to <13% moisture immediately. Do not feed moldy grain to animals. Apply trichoderma biofungicides preventively.',
    prevention: 'Resistant varieties, control insects that create kernel entry wounds, harvest early.',
    urgency: 'HIGH',
    imageHints: { dominantHue: [340, 20], lesionPattern: 'BLIGHT' },
  },

  // ─── BEAN ─────────────────────────────────────────────────────────────────
  {
    id: 'bean-rust',
    name: 'Bean Rust',
    crops: ['bean', 'common bean', 'kidney bean', 'climbing bean'],
    category: 'FUNGAL',
    symptoms: 'rust orange red brown circular pustules undersides leaves raised powdery spores reddish brown raised spots yellow halo ring',
    visualSigns: 'circular rust-orange/brown pustules mostly on leaf undersides with pale yellow halos above',
    management: 'Apply fungicide (mancozeb, tebuconazole) at first pustule detection. Remove infected leaves. Improve air flow by reducing plant density.',
    prevention: 'Resistant varieties, avoid wetting foliage with irrigation, crop rotation.',
    urgency: 'HIGH',
    imageHints: { dominantHue: [15, 35], lesionPattern: 'SPOTS' },
  },
  {
    id: 'bean-angular-leaf-spot',
    name: 'Angular Leaf Spot',
    crops: ['bean', 'common bean'],
    category: 'FUNGAL',
    symptoms: 'angular water soaked brown lesions bounded veins brown angular irregular spots grayish brown patches pods stems infected spots seeds',
    visualSigns: 'angular brownish water-soaked spots bounded by leaf veins, grey-brown on pods',
    management: 'Apply copper-based fungicide or mancozeb. Use certified disease-free seed. Remove plant debris.',
    prevention: 'Disease-free seed, avoid overhead irrigation, resistant varieties.',
    urgency: 'MEDIUM',
    imageHints: { dominantHue: [20, 50], lesionPattern: 'SPOTS' },
  },
  {
    id: 'bean-mosaic-virus',
    name: 'Bean Common Mosaic Virus (BCMV)',
    crops: ['bean', 'common bean'],
    category: 'VIRAL',
    symptoms: 'mottled mosaic green yellow irregular patches leaves distorted curled puckered stunted growth mosaic pattern aphid transmitted',
    visualSigns: 'irregular yellow-green mosaic mottling, leaf distortion and blistering, stunted plants',
    management: 'No cure. Rogue out infected plants immediately. Control aphid vectors with insecticidal soap or neem. Plant certified virus-free seed.',
    prevention: 'Virus-free seed, aphid control, resistant varieties (many modern beans are BCMV-resistant).',
    urgency: 'HIGH',
    imageHints: { lesionPattern: 'MOSAIC', yellowRatio: 'MEDIUM' },
  },
  {
    id: 'bean-root-rot',
    name: 'Bean Root Rot (Pythium/Fusarium)',
    crops: ['bean', 'common bean', 'soybean'],
    category: 'FUNGAL',
    symptoms: 'wilting despite moist soil brown black rotted roots stem base dark discoloration damping off seedlings collapsing poor emergence',
    visualSigns: 'brown-black water-soaked rotted roots and lower stem, plant wilts despite wet soil',
    management: 'Improve drainage, avoid waterlogged soils. Apply Trichoderma-based bio-fungicide to seed or soil. Reduce irrigation. Apply metalaxyl if Pythium.',
    prevention: 'Well-drained soil, raised beds in low areas, seed treatment with Thiram or Trichoderma.',
    urgency: 'MEDIUM',
  },
  {
    id: 'bean-anthracnose',
    name: 'Bean Anthracnose',
    crops: ['bean', 'common bean', 'cowpea'],
    category: 'FUNGAL',
    symptoms: 'sunken dark brown black oval lesions pods stems veins leaves reddish brown canker edges pink spores salmon pink ooze',
    visualSigns: 'sunken dark lesions on pods with salmon-pink spore masses, dark streaks on veins',
    management: 'Apply mancozeb or copper fungicide. Remove infected plant material. Use disease-free seed. Avoid handling wet plants.',
    prevention: 'Certified disease-free seed, crop rotation, well-drained plots.',
    urgency: 'HIGH',
    imageHints: { highNecrosis: true, lesionPattern: 'SPOTS' },
  },

  // ─── POTATO ───────────────────────────────────────────────────────────────
  {
    id: 'potato-late-blight',
    name: 'Potato Late Blight (Phytophthora infestans)',
    crops: ['potato', 'sweet potato'],
    category: 'FUNGAL',
    symptoms: 'dark brown water soaked lesions leaves white gray mold undersides rapid spread wet weather brown black tuber rot large blighted areas entire plant collapse',
    visualSigns: 'dark brown irregular water-soaked patches on leaves, white-grey mold on leaf undersides in wet conditions',
    management: 'Apply systemic fungicide (metalaxyl + mancozeb, dimethomorph) immediately. Remove and destroy infected plants. Do not compost. Harvest tubers promptly in dry weather.',
    prevention: 'Plant certified blight-resistant varieties, apply preventive fungicide before wet season, plant on ridges for drainage.',
    urgency: 'CRITICAL',
    imageHints: { highNecrosis: true, lesionPattern: 'BLIGHT', dominantHue: [15, 40] },
  },
  {
    id: 'potato-early-blight',
    name: 'Potato Early Blight (Alternaria solani)',
    crops: ['potato', 'tomato'],
    category: 'FUNGAL',
    symptoms: 'dark brown target board concentric ring spots older lower leaves yellow halo around lesion angular alternaria bullseye pattern',
    visualSigns: 'dark brown spots with concentric rings (target/bullseye pattern), yellow halo, starts on older lower leaves',
    management: 'Apply fungicide (chlorothalonil, mancozeb, azoxystrobin). Remove lower infected leaves. Ensure adequate potassium nutrition.',
    prevention: 'Crop rotation (3 years), resistant varieties, adequate plant nutrition.',
    urgency: 'MEDIUM',
    imageHints: { dominantHue: [20, 45], lesionPattern: 'SPOTS' },
  },
  {
    id: 'potato-bacterial-wilt',
    name: 'Potato Bacterial Wilt (Ralstonia solanacearum)',
    crops: ['potato', 'tomato', 'pepper', 'eggplant'],
    category: 'BACTERIAL',
    symptoms: 'sudden wilting one side plant brown discoloration vascular system cut stem ooze milky bacterial streaming wilt hot weather young healthy appearance then collapse',
    visualSigns: 'sudden wilting (often one-sided), cut stem shows brown vascular ring, bacterial ooze in water',
    management: 'No effective cure. Uproot and destroy infected plants. Do not replant solanaceous crops for 4+ years. Use resistant varieties, certified clean seed tubers.',
    prevention: 'Certified seed, resistant varieties, crop rotation, avoid flood irrigation that spreads bacteria.',
    urgency: 'CRITICAL',
    imageHints: { lesionPattern: 'WILT' },
  },
  {
    id: 'potato-virus-y',
    name: 'Potato Virus Y (PVY)',
    crops: ['potato', 'pepper', 'tomato'],
    category: 'VIRAL',
    symptoms: 'mosaic mottling yellowing leaves necrotic spots brown dead patches veins necrosis stunted malformed tubers yield loss aphid transmitted leaf drop',
    visualSigns: 'mosaic yellowing and brown/black necrotic spots on leaves, leaf rolling, stunted growth',
    management: 'Use certified virus-free seed tubers. Control aphid vectors. Rogue out infected plants early in the season.',
    prevention: 'Certified clean seed, aphid control, maintain clean borders, plant away from old potato fields.',
    urgency: 'HIGH',
    imageHints: { lesionPattern: 'MOSAIC', yellowRatio: 'MEDIUM' },
  },

  // ─── CASSAVA ──────────────────────────────────────────────────────────────
  {
    id: 'cassava-mosaic',
    name: 'Cassava Mosaic Disease (CMD)',
    crops: ['cassava'],
    category: 'VIRAL',
    symptoms: 'yellow green mosaic mottling distorted twisted chlorotic leaves chlorosis cupping rolling stunted reduced leaf size whitefly',
    visualSigns: 'yellow-green mosaic on distorted, misshapen leaves; severe cases show tiny crinkled yellow leaves',
    management: 'Use CMD-resistant or tolerant varieties. Remove severely infected plants. Control whitefly vector with insecticide. Plant disease-free cuttings.',
    prevention: 'Resistant varieties are critical, source clean planting material, control whiteflies.',
    urgency: 'HIGH',
    imageHints: { lesionPattern: 'MOSAIC', yellowRatio: 'HIGH' },
  },
  {
    id: 'cassava-brown-streak',
    name: 'Cassava Brown Streak Disease (CBSD)',
    crops: ['cassava'],
    category: 'VIRAL',
    symptoms: 'yellow chlorotic blotches leaves brown streak veins necrotic tuber brown corky dry rot inside tuber quality loss feathery chlorosis',
    visualSigns: 'yellow/brown leaf patches, brown streaks on veins, brown corky dry rot inside tubers',
    management: 'Plant CBSD-tolerant varieties (e.g. NAROCAS 1, Kiroba). Remove infected plants. Control whitefly. Only use clean stem cuttings.',
    prevention: 'CBSD-tolerant varieties, clean planting material, whitefly control. Avoid moving planting material from affected areas.',
    urgency: 'CRITICAL',
    imageHints: { dominantHue: [30, 60], lesionPattern: 'STRIPES', yellowRatio: 'MEDIUM' },
  },
  {
    id: 'cassava-bacterial-blight',
    name: 'Cassava Bacterial Blight (CBB)',
    crops: ['cassava'],
    category: 'BACTERIAL',
    symptoms: 'water soaked angular leaf spots brown blight wilting young shoots gum exudate canker stem blight dieback tip die dried leaves hang stem canker ooze',
    visualSigns: 'water-soaked angular leaf spots turning brown, wilting and dieback of shoot tips, gummy stem exudate',
    management: 'Plant resistant varieties. Remove and destroy infected material. Avoid injuring plants. Dip cuttings in copper bactericide before planting.',
    prevention: 'Resistant varieties, avoid wounding plants, use disease-free cuttings, copper sprays.',
    urgency: 'HIGH',
    imageHints: { highNecrosis: true, lesionPattern: 'BLIGHT' },
  },

  // ─── TOMATO ───────────────────────────────────────────────────────────────
  {
    id: 'tomato-late-blight',
    name: 'Tomato Late Blight',
    crops: ['tomato'],
    category: 'FUNGAL',
    symptoms: 'large dark brown greasy water soaked irregular patches leaves white mold undersides wet weather fruit brown rot rapid collapse all leaves blighted',
    visualSigns: 'large greasy dark patches on leaves, white mold on undersides, brown rotted fruit',
    management: 'Apply metalaxyl + mancozeb or cymoxanil fungicide immediately. Remove infected material. Avoid overhead irrigation.',
    prevention: 'Fungicide program before wet season, resistant varieties, stake plants for air flow.',
    urgency: 'CRITICAL',
    imageHints: { highNecrosis: true, lesionPattern: 'BLIGHT' },
  },
  {
    id: 'tomato-bacterial-speck',
    name: 'Tomato Bacterial Speck',
    crops: ['tomato'],
    category: 'BACTERIAL',
    symptoms: 'tiny dark brown black water soaked spots yellow halo small specks leaves fruit superficial spots greasy spots bacterial leaf dark specks',
    visualSigns: 'small dark brown specks on leaves with yellow halos, superficial dark spots on green fruit',
    management: 'Apply copper-based bactericide. Avoid overhead irrigation. Stake plants to reduce humidity.',
    prevention: 'Disease-free seed, copper sprays, avoid wetting foliage.',
    urgency: 'LOW',
    imageHints: { lesionPattern: 'SPOTS' },
  },
  {
    id: 'tomato-ylcv',
    name: 'Tomato Yellow Leaf Curl Virus (TYLCV)',
    crops: ['tomato'],
    category: 'VIRAL',
    symptoms: 'upward curling leaves yellow margins cupped edges stunted small plant yellowing leaf curl whitefly silver leaf curl compact plant',
    visualSigns: 'leaves curl upward with yellow margins, plants are severely stunted and bushy',
    management: 'No cure. Remove infected plants. Control whitefly vector with systemic insecticide (imidacloprid). Use yellow sticky traps. Plant resistant varieties.',
    prevention: 'TYLCV-resistant hybrids, whitefly management, insect-proof nursery, reflective mulch.',
    urgency: 'HIGH',
    imageHints: { lesionPattern: 'WILT', yellowRatio: 'HIGH' },
  },
  {
    id: 'tomato-fusarium-wilt',
    name: 'Tomato Fusarium Wilt',
    crops: ['tomato', 'pepper', 'eggplant'],
    category: 'FUNGAL',
    symptoms: 'one sided wilting yellowing lower older leaves vascular brown discoloration cut stem internal brown yellowing progressing upward plant death gradual wilt',
    visualSigns: 'one-sided or whole-plant wilting, yellow leaves starting from base, brown vascular discoloration inside stem',
    management: 'No cure for infected plants. Use resistant varieties (F1 hybrids with VF designation). Apply Trichoderma to soil before planting.',
    prevention: 'Resistant varieties, soil solarization, grafting on resistant rootstocks, 4-year rotation.',
    urgency: 'HIGH',
    imageHints: { lesionPattern: 'WILT' },
  },

  // ─── COFFEE ───────────────────────────────────────────────────────────────
  {
    id: 'coffee-leaf-rust',
    name: 'Coffee Leaf Rust (CLR)',
    crops: ['coffee', 'arabica', 'robusta'],
    category: 'FUNGAL',
    symptoms: 'yellow orange powdery spots undersides coffee leaves orange rust powder circular spots defoliation early leaf drop orange spore masses',
    visualSigns: 'bright orange/yellow powdery spots on leaf undersides, yellow patches visible from above, defoliation',
    management: 'Apply copper fungicide or triazole (triadimefon) at first sign. Apply preventively before rain season. Remove heavily infected branches.',
    prevention: 'Resistant varieties (Ruiru 11, Batian), shade management, timely preventive copper sprays.',
    urgency: 'HIGH',
    imageHints: { dominantHue: [20, 45], lesionPattern: 'SPOTS' },
  },
  {
    id: 'coffee-berry-disease',
    name: 'Coffee Berry Disease (CBD)',
    crops: ['coffee', 'arabica'],
    category: 'FUNGAL',
    symptoms: 'dark brown black sunken lesions green unripe berries mummified berries premature berry drop rotted soft berry dark spot colletotrichum',
    visualSigns: 'dark sunken lesions on green berries, premature berry drop, mummified black berries',
    management: 'Apply copper hydroxide or difenoconazole at berry initiation. Collect and destroy mummified berries. Prune for air circulation.',
    prevention: 'Resistant varieties, regular harvest of all berries (remove diseased), shade regulation.',
    urgency: 'CRITICAL',
    imageHints: { highNecrosis: true, lesionPattern: 'SPOTS' },
  },
  {
    id: 'coffee-berry-borer',
    name: 'Coffee Berry Borer (CBB)',
    crops: ['coffee', 'arabica', 'robusta'],
    category: 'PEST',
    symptoms: 'small round entry hole berry dark spot bored berries shriveled fallen berries weevil beetle insect damage premature drop berries',
    visualSigns: 'tiny round entry hole at berry tip, infested berries shriveled and full of frass',
    management: 'Harvest all mature berries promptly (no leaving on tree). Collect fallen berries. Apply Beauveria bassiana (entomopathogenic fungus). Set traps with methanol/ethanol.',
    prevention: 'Meticulous harvest discipline (leave no berries on tree), Beauveria bassiana spray, CBB traps.',
    urgency: 'HIGH',
  },

  // ─── BANANA ───────────────────────────────────────────────────────────────
  {
    id: 'banana-xanthomonas-wilt',
    name: 'Banana Xanthomonas Wilt (BXW)',
    crops: ['banana', 'plantain', 'matoke'],
    category: 'BACTERIAL',
    symptoms: 'wilting yellowing leaves flower premature ripening uneven ripening yellow bacterial ooze internal rotting stem cross section yellow rot whole bunch collapse',
    visualSigns: 'premature wilting and yellowing, uneven/premature ripening of bunches, yellow bacterial ooze from cut stem',
    management: 'Remove and destroy entire mat. Sterilize cutting tools between plants with bleach. Do NOT compost infected material. Establish 50 m buffer. Report to extension officer.',
    prevention: 'No infected planting material, sterilize tools, remove male buds early in season, quarantine affected areas.',
    urgency: 'CRITICAL',
    imageHints: { lesionPattern: 'WILT', yellowRatio: 'HIGH' },
  },
  {
    id: 'banana-black-sigatoka',
    name: 'Black Sigatoka Leaf Streak',
    crops: ['banana', 'plantain', 'matoke'],
    category: 'FUNGAL',
    symptoms: 'dark brown black streaks stripes leaves narrow streaks enlarge yellow halo early yellowing defoliation premature bunch ripening streaks leaves',
    visualSigns: 'dark brown to black narrow streaks on leaves with yellow halos, severe defoliation',
    management: 'Apply systemic fungicide (propiconazole, trifloxystrobin). Remove and destroy badly infected leaves. Maintain 1-2 healthy leaves per plant minimum.',
    prevention: 'Resistant varieties (FHIA hybrids), regular leaf removal, adequate spacing for air circulation.',
    urgency: 'HIGH',
    imageHints: { highNecrosis: true, lesionPattern: 'STRIPES' },
  },
  {
    id: 'banana-fusarium-wilt',
    name: 'Banana Fusarium Wilt (Panama Disease TR4)',
    crops: ['banana', 'plantain'],
    category: 'FUNGAL',
    symptoms: 'yellowing lower oldest leaves wilting collapse internal brown vascular discoloration red yellow internal rot pseudostem sudden collapse one plant wilt spreading',
    visualSigns: 'yellowing and wilting starting from oldest leaves, brown vascular discoloration inside pseudostem',
    management: 'No effective treatment. Destroy infected mats. Do not replant susceptible varieties. Use TR4-resistant varieties where available. Report to plant health authorities.',
    prevention: 'TR4-resistant or tolerant varieties, avoid movement of soil from infected areas, strict tool hygiene.',
    urgency: 'CRITICAL',
    imageHints: { lesionPattern: 'WILT', yellowRatio: 'HIGH' },
  },

  // ─── SORGHUM ──────────────────────────────────────────────────────────────
  {
    id: 'sorghum-anthracnose',
    name: 'Sorghum Anthracnose',
    crops: ['sorghum'],
    category: 'FUNGAL',
    symptoms: 'circular red tan elliptical lesions leaves salmon pink spore masses reddish spots leaf sheath rot stalk rot grain discoloration',
    visualSigns: 'circular red/tan lesions with dark borders and salmon spore masses, stalk red-rot visible at cut',
    management: 'Use resistant varieties. Apply fungicide (carbendazim). Crop rotation. Remove infected debris.',
    prevention: 'Resistant varieties, crop rotation, remove debris, balanced fertilisation.',
    urgency: 'MEDIUM',
  },
  {
    id: 'sorghum-downy-mildew',
    name: 'Sorghum Downy Mildew',
    crops: ['sorghum', 'maize', 'corn'],
    category: 'FUNGAL',
    symptoms: 'white downy growth undersides young leaves systemic infection entire leaves pale green white stripes yellowing green white striped',
    visualSigns: 'pale green/yellow stripes on young leaves, white downy growth on leaf undersides',
    management: 'Apply metalaxyl seed treatment. Remove infected plants. Plant resistant varieties.',
    prevention: 'Seed treatment, resistant varieties, crop rotation, good drainage.',
    urgency: 'HIGH',
    imageHints: { lesionPattern: 'STRIPES', yellowRatio: 'HIGH' },
  },

  // ─── RICE ─────────────────────────────────────────────────────────────────
  {
    id: 'rice-blast',
    name: 'Rice Blast (Magnaporthe oryzae)',
    crops: ['rice', 'upland rice'],
    category: 'FUNGAL',
    symptoms: 'diamond spindle shaped gray brown lesions leaves neck rot blast neck snapping dark brown border gray center panicle sterile head blast node infection',
    visualSigns: 'diamond-shaped lesions with grey centre and brown border on leaves, rotted/broken neck at panicle base',
    management: 'Apply tricyclazole or isoprothiolane fungicide. Balanced nitrogen (avoid excess N). Plant resistant varieties.',
    prevention: 'Resistant varieties, balanced fertilisation, avoid excess nitrogen, preventive fungicide during humid conditions.',
    urgency: 'HIGH',
    imageHints: { dominantHue: [15, 50], lesionPattern: 'SPOTS' },
  },
  {
    id: 'rice-bacterial-leaf-blight',
    name: 'Rice Bacterial Leaf Blight (BLB)',
    crops: ['rice'],
    category: 'BACTERIAL',
    symptoms: 'water soaked greasy yellow stripe leaf margins creamy yellow blight entire leaf wilting bacterial leaf scorch lesions expand margin',
    visualSigns: 'straw-yellow lesions from leaf tip or margin progressing toward base, creamy bacterial ooze in severe cases',
    management: 'Apply copper bactericide. Drain field temporarily. Reduce nitrogen. Plant resistant varieties.',
    prevention: 'Resistant varieties, balanced nutrition (avoid excess N), use disease-free seed.',
    urgency: 'HIGH',
    imageHints: { dominantHue: [50, 75], lesionPattern: 'BLIGHT', yellowRatio: 'HIGH' },
  },

  // ─── NUTRIENT DEFICIENCIES (EXPANDED) ─────────────────────────────────────
  {
    id: 'nitrogen-def',
    name: 'Nitrogen Deficiency',
    crops: ['maize', 'bean', 'potato', 'tomato', 'rice', 'sorghum', 'cassava', 'banana', 'coffee'],
    category: 'NUTRIENT',
    symptoms: 'yellowing older lower leaves general pale chlorosis yellow pale light green entire plant stunted slow growth thin stems pale uniform yellowing',
    visualSigns: 'uniform yellowing starting from oldest/lower leaves, pale green overall plant colour',
    management: 'Apply urea (46-0-0) or CAN at 50-100 kg/ha in split doses. Incorporate composted manure. Confirm with soil test.',
    prevention: 'Regular soil testing, planned fertilizer program, incorporate legumes in rotation.',
    urgency: 'MEDIUM',
    imageHints: { yellowRatio: 'HIGH', dominantHue: [55, 80] },
  },
  {
    id: 'phosphorus-def',
    name: 'Phosphorus Deficiency',
    crops: ['maize', 'bean', 'potato', 'cassava', 'sorghum', 'rice'],
    category: 'NUTRIENT',
    symptoms: 'dark green purple reddish leaves purplish coloration stems undersides delayed flowering maturity stunted roots poor root development reddish purple tinge',
    visualSigns: 'dark green to purple discolouration of leaves and stems (especially undersides), stunted plant',
    management: 'Apply DAP or TSP (18-46-0) at planting. Correct acidic soil pH > 5.5 with lime. Place fertilizer near root zone.',
    prevention: 'Soil testing before planting, lime acidic soils, incorporate manure which helps release phosphorus.',
    urgency: 'MEDIUM',
    imageHints: { dominantHue: [270, 330] },
  },
  {
    id: 'potassium-def',
    name: 'Potassium Deficiency',
    crops: ['maize', 'bean', 'potato', 'banana', 'cassava', 'tomato'],
    category: 'NUTRIENT',
    symptoms: 'yellow brown scorching leaf edges margins older leaves marginal necrosis firing leaf tip burn dried edges weak stems poor fruit fill lodging',
    visualSigns: 'yellow-brown scorching/burning at leaf edges and tips of older leaves, dry brown margins',
    management: 'Apply MOP (muriate of potash 0-0-60) or NPK blend with K. Avoid excess nitrogen without matching potassium.',
    prevention: 'Balanced NPK fertilization, soil testing, avoid excess N application.',
    urgency: 'MEDIUM',
    imageHints: { highNecrosis: true, dominantHue: [25, 55] },
  },
  {
    id: 'iron-def',
    name: 'Iron Deficiency (Chlorosis)',
    crops: ['bean', 'soybean', 'tomato', 'potato', 'coffee'],
    category: 'NUTRIENT',
    symptoms: 'interveinal chlorosis yellowing between veins young new leaves green veins yellow interveinal yellowing new growth affected first young pale',
    visualSigns: 'yellow tissue between green veins (interveinal chlorosis) on young/new leaves',
    management: 'Apply iron chelate foliar spray (FeSO4). Lower soil pH if alkaline (>7.0). Improve drainage. Avoid over-liming.',
    prevention: 'Maintain pH 5.5-6.5, avoid over-irrigation (reduces oxygen and iron availability), soil testing.',
    urgency: 'LOW',
    imageHints: { yellowRatio: 'MEDIUM', dominantHue: [55, 80] },
  },

  // ─── WATER STRESS ─────────────────────────────────────────────────────────
  {
    id: 'drought-stress',
    name: 'Drought / Water Stress',
    crops: ['maize', 'bean', 'potato', 'tomato', 'sorghum', 'cassava', 'banana', 'coffee', 'rice'],
    category: 'WATER',
    symptoms: 'wilting drooping curling rolling leaves dry cracked soil plant wilt afternoon recover morning turgid drought stressed scorched leaf tips desiccated',
    visualSigns: 'leaf rolling/wilting (worst in afternoon, recovers morning), dry cracked soil, scorched brown leaf tips',
    management: 'Irrigate deeply and less frequently. Apply mulch 5-10 cm around plants. Prioritize irrigation at flowering/fruiting. Consider drought-tolerant varieties for future season.',
    prevention: 'Mulching, drip irrigation, drought-tolerant varieties, planting on soil with good water holding capacity.',
    urgency: 'HIGH',
  },
  {
    id: 'waterlogging',
    name: 'Waterlogging / Excess Moisture',
    crops: ['maize', 'bean', 'potato', 'tomato', 'coffee'],
    category: 'WATER',
    symptoms: 'yellowing wilting despite wet soggy moist soil waterlogged flooded poor drainage standing water root rot yellow lower leaves wet feet stunted',
    visualSigns: 'yellowing/wilting despite visibly wet soil, standing water around plants, soil is soggy',
    management: 'Open drainage furrows immediately. Stop irrigation. Raise beds if persistent. Apply Trichoderma to mitigate secondary root rot.',
    prevention: 'Raised beds on slopes/low areas, adequate field drainage, avoid irrigation after heavy rain.',
    urgency: 'HIGH',
  },
];
